In [91]:
import pandas as pd
import numpy as np

#### 1) A Box-office hit film means a film which has grossed $20,00,000. Find the number of Box-Office Hit Films.

In [92]:
data = pd.read_csv(r"C:\Users\ADMIN\Downloads\Netflix.csv")
data.head()

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,View Rating,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",R,7.9,98.0,82.0,57.0,"$2,122,065",12-Dec-08,04-03-2021,https://www.netflix.com/watch/81415947,205926.0
1,HOW TO BUILD A GIRL,Comedy,English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,"Paddy Considine, Cleo, Beanie Feldstein, Dónal...",R,5.8,79.0,69.0,NaN,"$70,632",08-May-20,04-03-2021,https://www.netflix.com/watch/81041267,2838.0
2,Centigrade,"Drama, Thriller",English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon","Genesis Rodriguez, Vincent Piazza",Unrated,4.3,NaN,46.0,NaN,"$16,263",28-Aug-20,04-03-2021,https://www.netflix.com/watch/81305978,1720.0
3,ANNE+,Drama,Turkish,Series,7.7,"Belgium,Netherlands",< 30 minutes,NaN,NaN,"Vahide Perçin, Gonca Vuslateri, Cansu Dere, Be...",NaN,6.5,NaN,NaN,NaN,NaN,01-Oct-16,04-03-2021,https://www.netflix.com/watch/81336456,1147.0
4,Moxie,"Animation, Short, Drama",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,NaN,Ragga Gudrun,NaN,6.3,NaN,NaN,4.0,NaN,22-Sep-11,04-03-2021,https://www.netflix.com/watch/81078393,63.0

In [93]:
data.isnull().sum()

Title                     6256
Genre                     7597
Languages                 7805
Series or Movie           6256
Hidden Gem Score          7878
Country Availability      6267
Runtime                   6256
Director                  9407
Writer                    9356
Actors                    7748
View Rating              11484
IMDb Score                7737
Rotten Tomatoes Score    12712
Metacritic Score         13825
Awards Nominated For     11713
Boxoffice                14049
Release Date              7687
Netflix Release Date      6115
Netflix Link              6115
IMDb Votes                7738
dtype: int64

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15483 entries, 0 to 15482
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  9227 non-null   object
 1   Genre                  7886 non-null   object
 2   Languages              7678 non-null   object
 3   Series or Movie        9227 non-null   object
 4   Hidden Gem Score       7605 non-null   float64
 5   Country Availability   9216 non-null   object
 6   Runtime                9227 non-null   object
 7   Director               6076 non-null   object
 8   Writer                 6127 non-null   object
 9   Actors                 7735 non-null   object
 10  View Rating            3999 non-null   object
 11  IMDb Score             7746 non-null   float64
 12  Rotten Tomatoes Score  2771 non-null   float64
 13  Metacritic Score       1658 non-null   float64
 14  Awards Nominated For   3770 non-null   float64
 15  Boxoffice              1434 non-null   object
 16  Release Date           7796 non-null   object
 17  Netflix Release Date   9368 non-null   object
 18  Netflix Link           9368 non-null   object
 19  IMDb Votes             7745 non-null   float64
dtypes: float64(6), object(14)
memory usage: 2.4+ MB

In [95]:
data.dropna(inplace = True)

In [96]:
data.columns

Index(['Title', 'Genre', 'Languages', 'Series or Movie', 'Hidden Gem Score',
       'Country Availability', 'Runtime', 'Director', 'Writer', 'Actors',
       'View Rating', 'IMDb Score', 'Rotten Tomatoes Score',
       'Metacritic Score', 'Awards Nominated For', 'Boxoffice', 'Release Date',
       'Netflix Release Date', 'Netflix Link', 'IMDb Votes'],
      dtype='object')

In [97]:
data["Gross"]= data["Boxoffice"].str.replace("$","").str.replace(",","").astype(float)

In [98]:
data.head()

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",...,7.9,98.0,82.0,57.0,"$2,122,065",12-Dec-08,04-03-2021,https://www.netflix.com/watch/81415947,205926.0,2122065.0
11,The Invisible,"Crime, Drama, Fantasy, Mystery, Thriller",English,Movie,2.0,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David S. Goyer,"Christine Roum, Mats Wahl, Mick Davis","Marcia Gay Harden, Chris Marquette, Margarita ...",...,6.2,20.0,36.0,1.0,"$20,578,909",27-Apr-07,03-03-2021,https://www.netflix.com/watch/81382078,34738.0,20578909.0
15,Joker,"Crime, Drama, Thriller",English,Movie,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Todd Phillips,"Scott Silver, Jerry Robinson, Todd Phillips, B...","Joaquin Phoenix, Zazie Beetz, Robert De Niro, ...",...,8.4,68.0,59.0,228.0,"$335,451,311",04-Oct-19,03-03-2021,https://www.netflix.com/watch/81382215,951938.0,335451311.0
16,I,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Movie,2.8,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,6.5,52.0,51.0,69.0,"$474,544,677",19-May-99,03-03-2021,https://www.netflix.com/watch/81382114,733336.0,474544677.0
17,Harrys Daughters,"Adventure, Drama, Fantasy, Mystery",English,Movie,4.4,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David Yates,"Steve Kloves, J.K. Rowling","Ralph Fiennes, Alan Rickman, Michael Gambon, D...",...,8.1,96.0,85.0,94.0,"$381,409,310",15-Jul-11,03-03-2021,https://www.netflix.com/watch/81382102,766594.0,381409310.0

In [99]:
data[data["Gross"]>=2000000]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",...,7.9,98.0,82.0,57.0,"$2,122,065",12-Dec-08,04-03-2021,https://www.netflix.com/watch/81415947,205926.0,2122065.0
11,The Invisible,"Crime, Drama, Fantasy, Mystery, Thriller",English,Movie,2.0,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David S. Goyer,"Christine Roum, Mats Wahl, Mick Davis","Marcia Gay Harden, Chris Marquette, Margarita ...",...,6.2,20.0,36.0,1.0,"$20,578,909",27-Apr-07,03-03-2021,https://www.netflix.com/watch/81382078,34738.0,20578909.0
15,Joker,"Crime, Drama, Thriller",English,Movie,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Todd Phillips,"Scott Silver, Jerry Robinson, Todd Phillips, B...","Joaquin Phoenix, Zazie Beetz, Robert De Niro, ...",...,8.4,68.0,59.0,228.0,"$335,451,311",04-Oct-19,03-03-2021,https://www.netflix.com/watch/81382215,951938.0,335451311.0
16,I,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Movie,2.8,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,6.5,52.0,51.0,69.0,"$474,544,677",19-May-99,03-03-2021,https://www.netflix.com/watch/81382114,733336.0,474544677.0
17,Harrys Daughters,"Adventure, Drama, Fantasy, Mystery",English,Movie,4.4,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David Yates,"Steve Kloves, J.K. Rowling","Ralph Fiennes, Alan Rickman, Michael Gambon, D...",...,8.1,96.0,85.0,94.0,"$381,409,310",15-Jul-11,03-03-2021,https://www.netflix.com/watch/81382102,766594.0,381409310.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9195,CHIPS,"Action, Comedy, Crime","English, Spanish",Movie,1.8,"Brazil,Argentina,Mexico,Colombia,South Korea",1-2 hour,Dax Shepard,"Rick Rosner, Dax Shepard","Vincent D'Onofrio, Michael Peña, Dax Shepard, ...",...,6.0,18.0,28.0,1.0,"$18,600,152",24-Mar-17,26-12-2017,https://www.netflix.com/watch/80163158,42597.0,18600152.0
9211,The Nut Job 2: Nutty by Nature,"Animation, Adventure, Comedy, Family, Fantasy",English,Movie,3.8,"South Korea,Romania,Hungary,Brazil,Czech Repub...",1-2 hour,Cal Brunker,"Bob Barlen, Scott Bindley, Peter Lepeniotis, C...","Bobby Moynihan, Maya Rudolph, Bobby Cannavale,...",...,5.5,14.0,36.0,3.0,"$28,370,522",11-Aug-17,19-12-2017,https://www.netflix.com/watch/80067832,5931.0,28370522.0
9213,The Brothers Grimsby,"Action, Adventure, Comedy, Crime, Thriller","English, Ukrainian",Movie,2.4,"Canada,Iceland,Australia",1-2 hour,Louis Leterrier,"Peter Baynham, Phil Johnston, Sacha Baron Cohen","Freddie Crowder, Rebel Wilson, Sacha Baron Coh...",...,6.2,37.0,44.0,1.0,"$6,874,837",11-Mar-16,18-12-2017,https://www.netflix.com/watch/80079256,93608.0,6874837.0
9221,The Foreigner,"Action, Thriller","English, Mandarin",Movie,3.2,"United Kingdom,Australia,South Korea,Turkey,Hu...",1-2 hour,Martin Campbell,"Stephen Leather, David Marconi","Mark Tandy, Rufus Jones, Katie Leung, Jackie Chan",...,7.0,65.0,55.0,1.0,"$34,393,507",13-Oct-17,15-12-2017,https://www.netflix.com/watch/80185765,102492.0,34393507.0
9226,Bad Education,"Crime, Drama","Spanish, Latin",Movie,4.1,Spain,1-2 hour,Pedro Almodóvar,Pedro Almodóvar,"Fele Martínez, Gael García Bernal, Lluís Homar...",...,7.4,88.0,81.0,42.0,"$5,284,284",11-Feb-05,15-12-2017,https://www.netflix.com/watch/70011205,55919.0,5284284.0

In [100]:
hit = data[data["Gross"]>=2000000]
print("Hit Movies:",hit["Title"].count())

Hit Movies: 551

In [101]:
data["hit"] = data["Gross"]>=2000000

In [102]:
data.head()

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",...,98.0,82.0,57.0,"$2,122,065",12-Dec-08,04-03-2021,https://www.netflix.com/watch/81415947,205926.0,2122065.0,True
11,The Invisible,"Crime, Drama, Fantasy, Mystery, Thriller",English,Movie,2.0,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David S. Goyer,"Christine Roum, Mats Wahl, Mick Davis","Marcia Gay Harden, Chris Marquette, Margarita ...",...,20.0,36.0,1.0,"$20,578,909",27-Apr-07,03-03-2021,https://www.netflix.com/watch/81382078,34738.0,20578909.0,True
15,Joker,"Crime, Drama, Thriller",English,Movie,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Todd Phillips,"Scott Silver, Jerry Robinson, Todd Phillips, B...","Joaquin Phoenix, Zazie Beetz, Robert De Niro, ...",...,68.0,59.0,228.0,"$335,451,311",04-Oct-19,03-03-2021,https://www.netflix.com/watch/81382215,951938.0,335451311.0,True
16,I,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Movie,2.8,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",19-May-99,03-03-2021,https://www.netflix.com/watch/81382114,733336.0,474544677.0,True
17,Harrys Daughters,"Adventure, Drama, Fantasy, Mystery",English,Movie,4.4,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David Yates,"Steve Kloves, J.K. Rowling","Ralph Fiennes, Alan Rickman, Michael Gambon, D...",...,96.0,85.0,94.0,"$381,409,310",15-Jul-11,03-03-2021,https://www.netflix.com/watch/81382102,766594.0,381409310.0,True

In [103]:
hit_count = data.groupby("hit")["Gross"].count()
print("Hitmovies:",hit_count)

Hitmovies: hit
False    237
True     551
Name: Gross, dtype: int64

#### 2) A critically acclaimed movie means a film that has IMDB rating of at least 8. Find the number of such films.

In [104]:
critically_acclaimed = data[data["IMDb Score"]>=8]
print("critically_acclaimed:",critically_acclaimed["Title"].count())

critically_acclaimed: 35

#### 3) Find all critically acclaimed movies which were Box-Office Hits.

In [105]:
m = data[(data["IMDb Score"]>=8) & (data["Gross"]>=2000000)].Title.count()
print("Hit & Critically Claimed Movies:",m)

Hit & Critically Claimed Movies: 31

#### 4) Find all critically acclaimed movies which has received at least 5 awards. Order them according to the number of awards.

In [106]:
movie = data[(data["IMDb Score"]>=8) & (data["Awards Nominated For"]>=5)]
print(movie[["Title","Awards Nominated For"]].sort_values(by = "Awards Nominated For"))

                                          Title  Awards Nominated For
3364                       Black Cat, White Cat                   5.0
69                                  Stand by Me                  11.0
4765                    They Shall Not Grow Old                  11.0
6635                Blade Runner: The Final Cut                  19.0
3633                       Howl’s Moving Castle                  20.0
421                            The Elephant Man                  22.0
6859                                      Alien                  22.0
1359                                     Aliens                  23.0
8259                                     Aliens                  23.0
4008                    The Biggest Little Farm                  28.0
7190                                     Wonder                  29.0
2790                                      2 дня                  33.0
2841                       Честное пионерское 2                  33.0
6235                         Dances with Wolves                  38.0
6237                              Casino Royale                  44.0
697                       Me & You vs The World                  46.0
4425                        Gods Little Village                  49.0
1748                                   Sin City                  54.0
5341          Spider-Man: Into the Spider-Verse                  55.0
6187                                   Magnolia                  59.0
295                                    The Hunt                  70.0
865                                    Fiction.                  75.0
17                             Harrys Daughters                  94.0
2844                       Честное пионерское 3                  95.0
4869                                 Green Book                 119.0
1338                                  Spotlight                 143.0
7098                          Blade Runner 2049                 154.0
1218                                       1917                 180.0
1139                              Girls Revenge                 187.0
4603  Three Billboards Outside Ebbing, Missouri                 225.0
1722                                      Joker                 228.0
15                                        Joker                 228.0
1595                                   Parasite                 262.0

#### 5) Find all critically acclaimed tv series for United States.

In [107]:
data[(data["IMDb Score"]>=8) & (data["Country Availability"]=="United States")]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit
6235,Dances with Wolves,"Adventure, Drama, Western","English, Sioux, Pawnee",Movie,3.9,United States,> 2 hrs,Kevin Costner,Michael Blake,"Rodney A. Grant, Kevin Costner, Mary McDonnell...",...,83.0,72.0,38.0,"$184,208,848",21-Nov-90,01-02-2019,https://www.netflix.com/watch/60028940,240656.0,184208848.0,True
6237,Casino Royale,"Action, Adventure, Thriller","English, Serbian, German, Italian, French",Movie,4.2,United States,> 2 hrs,Martin Campbell,"Neal Purvis, Paul Haggis, Ian Fleming, Robert ...","Mads Mikkelsen, Judi Dench, Daniel Craig, Eva ...",...,94.0,80.0,44.0,"$167,445,960",17-Nov-06,01-02-2019,https://www.netflix.com/watch/70044604,582997.0,167445960.0,True

#### 6) IMDB Rating is based on IMDB Votes. Find all films which inspite of receiving at least. 100 votes did not receive any award.

In [108]:
data[(data["IMDb Votes"]>=100)&(data["Awards Nominated For"]==0)]

Empty DataFrame
Columns: [Title, Genre, Languages, Series or Movie, Hidden Gem Score, Country Availability, Runtime, Director, Writer, Actors, View Rating, IMDb Score, Rotten Tomatoes Score, Metacritic Score, Awards Nominated For, Boxoffice, Release Date, Netflix Release Date, Netflix Link, IMDb Votes, Gross, hit]
Index: []

[0 rows x 22 columns]

In [109]:
data.head()

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",...,98.0,82.0,57.0,"$2,122,065",12-Dec-08,04-03-2021,https://www.netflix.com/watch/81415947,205926.0,2122065.0,True
11,The Invisible,"Crime, Drama, Fantasy, Mystery, Thriller",English,Movie,2.0,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David S. Goyer,"Christine Roum, Mats Wahl, Mick Davis","Marcia Gay Harden, Chris Marquette, Margarita ...",...,20.0,36.0,1.0,"$20,578,909",27-Apr-07,03-03-2021,https://www.netflix.com/watch/81382078,34738.0,20578909.0,True
15,Joker,"Crime, Drama, Thriller",English,Movie,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Todd Phillips,"Scott Silver, Jerry Robinson, Todd Phillips, B...","Joaquin Phoenix, Zazie Beetz, Robert De Niro, ...",...,68.0,59.0,228.0,"$335,451,311",04-Oct-19,03-03-2021,https://www.netflix.com/watch/81382215,951938.0,335451311.0,True
16,I,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Movie,2.8,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",19-May-99,03-03-2021,https://www.netflix.com/watch/81382114,733336.0,474544677.0,True
17,Harrys Daughters,"Adventure, Drama, Fantasy, Mystery",English,Movie,4.4,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David Yates,"Steve Kloves, J.K. Rowling","Ralph Fiennes, Alan Rickman, Michael Gambon, D...",...,96.0,85.0,94.0,"$381,409,310",15-Jul-11,03-03-2021,https://www.netflix.com/watch/81382102,766594.0,381409310.0,True

#### 7) A popular film means it is released at Netflix platforms within 1 year. Find all Films which were released in Netflix within 2 years of actual release.

In [110]:
data['Release Date'] = pd.to_datetime(data['Release Date'], format='%d/%m/%Y', errors='coerce')
data['Netflix Release Date'] = pd.to_datetime(data['Netflix Release Date'], format='%d/%m/%Y', errors='coerce')

popular_films = data[(data['Series or Movie'] == 'Movie') & ((data['Netflix Release Date'] - data['Release Date']).dt.days <= 365)]
popular_films.head()

Empty DataFrame
Columns: [Title, Genre, Languages, Series or Movie, Hidden Gem Score, Country Availability, Runtime, Director, Writer, Actors, View Rating, IMDb Score, Rotten Tomatoes Score, Metacritic Score, Awards Nominated For, Boxoffice, Release Date, Netflix Release Date, Netflix Link, IMDb Votes, Gross, hit]
Index: []

[0 rows x 22 columns]

#### 8) Find all popular films which are available in Canada.

In [111]:
popular_films_canada = popular_films[popular_films['Country Availability'].str.contains('Canada', na=False)]
popular_films_canada

Empty DataFrame
Columns: [Title, Genre, Languages, Series or Movie, Hidden Gem Score, Country Availability, Runtime, Director, Writer, Actors, View Rating, IMDb Score, Rotten Tomatoes Score, Metacritic Score, Awards Nominated For, Boxoffice, Release Date, Netflix Release Date, Netflix Link, IMDb Votes, Gross, hit]
Index: []

[0 rows x 22 columns]

#### 9) Find all movies which have a runtime of at least 1 hour.

In [112]:
movies_runtime = data[(data['Series or Movie'] == 'Movie') & (data['Runtime'].str.contains("1",na = False))]
movies_runtime[['Title','Runtime']]

                        Title   Runtime
11              The Invisible  1-2 hour
15                      Joker  1-2 hour
16                          I  1-2 hour
17           Harrys Daughters  1-2 hour
28                 The Closet  1-2 hour
...                       ...       ...
9213     The Brothers Grimsby  1-2 hour
9221            The Foreigner  1-2 hour
9224               Live Flesh  1-2 hour
9225  The Flower of My Secret  1-2 hour
9226            Bad Education  1-2 hour

[580 rows x 2 columns]

### 10) Find all tv series which have been created with more than 1 language.

In [113]:
tv_multi_lang = data[(data['Series or Movie'] == 'Series') & (data['Languages'].str.contains(',', na=False))]

In [114]:
tv_multi_lang

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,"Kåre Hedebrant, Per Ragnar, Lina Leandersson, ...",...,98.0,82.0,57.0,"$2,122,065",NaT,NaT,https://www.netflix.com/watch/81415947,205926.0,2122065.0,True
54,Alice,"Comedy, Romance","English, Cantonese",Series,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",< 30 minutes,Woody Allen,Woody Allen,"June Squibb, Mia Farrow, William Hurt, Joe Man...",...,75.0,67.0,7.0,"$7,331,647",NaT,NaT,https://www.netflix.com/watch/81404896,13379.0,7331647.0,True
307,Im Home,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Series,2.8,"Thailand,Singapore,Malaysia,Hong Kong",< 30 minutes,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",NaT,NaT,https://www.netflix.com/watch/81351300,733336.0,474544677.0,True
368,Lupin,"Animation, Adventure, Family, Fantasy","Japanese, English, French",Series,4.0,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",< 30 minutes,Hayao Miyazaki,"Haruya Yamazaki, Hayao Miyazaki, Mary Claypool...","Kiyoshi Kobayashi, Makio Inoue, Yasuo Yamada, ...",...,95.0,71.0,1.0,"$142,425",NaT,NaT,https://www.netflix.com/watch/80994082,27154.0,142425.0,False
490,Evils Wave,Drama,"Swedish, Finnish",Series,3.5,Japan,< 30 minutes,Mikael Håfström,"Hans Gunnarsson, Jan Guillou, Mikael Håfström","Henrik Lundström, Linda Zilliacus, Andreas Wil...",...,68.0,61.0,10.0,"$15,530",NaT,NaT,https://www.netflix.com/watch/81367819,35722.0,15530.0,False
742,Babel,Drama,"English, Arabic, Spanish, Japanese, Berber lan...",Series,3.5,South Korea,< 30 minutes,Alejandro G. Iñárritu,"Guillermo Arriaga, Alejandro G. Iñárritu","Brad Pitt, Mohamed Akhzam, Cate Blanchett, Pet...",...,69.0,69.0,136.0,"$34,302,837",NaT,NaT,https://www.netflix.com/watch/81380153,289958.0,34302837.0,True
998,Im Standing on a Million Lives,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Series,2.8,Japan,< 30 minutes,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",NaT,NaT,https://www.netflix.com/watch/81341942,733336.0,474544677.0,True
1125,The Liberator,"Biography, Drama, History","Spanish, English, French",Series,5.1,"Lithuania,Australia,United Kingdom,Poland,Braz...",< 30 minutes,Alberto Arvelo,Timothy J. Sexton,"Juana Acosta, Edgar Ramírez, Erich Wildpret, M...",...,38.0,51.0,3.0,"$113,067",NaT,NaT,https://www.netflix.com/watch/81019775,5038.0,113067.0,False
1162,Love & Anarchy,"Drama, Romance","English, French",Series,2.5,"Lithuania,Mexico,Australia,Poland,France,Brazi...",< 30 minutes,Gaspar Noé,Gaspar Noé,"Klara Kristin, Ugo Fox, Karl Glusman, Aomi Muyock",...,40.0,51.0,1.0,"$249,083",NaT,NaT,https://www.netflix.com/watch/81069541,48843.0,249083.0,False
1184,Evil,Drama,"Swedish, Finnish",Series,3.5,United States,< 30 minutes,Mikael Håfström,"Hans Gunnarsson, Jan Guillou, Mikael Håfström","Henrik Lundström, Linda Zilliacus, Andreas Wil...",...,68.0,61.0,10.0,"$15,530",NaT,NaT,https://www.netflix.com/watch/81190640,35722.0,15530.0,False
1242,The Queens Gambit,"Biography, Drama, History","English, German, French",Series,4.3,"Lithuania,Canada,Australia,Poland,Mexico,Franc...",< 30 minutes,Stephen Frears,Peter Morgan,"Alex Jennings, Roger Allam, James Cromwell, He...",...,96.0,91.0,97.0,"$56,441,711",NaT,NaT,https://www.netflix.com/watch/80234304,104495.0,56441711.0,True
1567,Outbreak,"Action, Drama, Thriller","English, Korean, French",Series,3.1,Japan,< 30 minutes,Wolfgang Petersen,"Robert Roy Pool, Laurence Dworet","Dustin Hoffman, Rene Russo, Morgan Freeman, Ke...",...,59.0,64.0,5.0,"$67,659,560",NaT,NaT,https://www.netflix.com/watch/81314896,120516.0,67659560.0,True
1610,Chefs Table: BBQ,"Adventure, Comedy, Drama","English, Spanish",Series,3.8,"Lithuania,Canada,Australia,Poland,Mexico,Brazi...",< 30 minutes,Jon Favreau,Jon Favreau,"John Leguizamo, Jon Favreau, Emjay Anthony, Bo...",...,87.0,68.0,4.0,"$31,424,003",NaT,NaT,https://www.netflix.com/watch/81292974,197249.0,31424003.0,True
1746,Worlds Most Wanted,"Action, Adventure, Horror, Sci-Fi","English, Spanish, Hebrew, Arabic",Series,3.3,"Switzerland,Czech Republic,United States,Unite...",< 30 minutes,Marc Forster,"Damon Lindelof, Matthew Michael Carnahan, Drew...","Brad Pitt, Daniella Kertesz, Mireille Enos, Ja...",...,66.0,63.0,24.0,"$202,359,711",NaT,NaT,https://www.netflix.com/watch/81013210,602843.0,202359711.0,True
1860,Meet the Parents,"Comedy, Romance","English, Thai, Spanish, Hebrew, French",Series,3.8,United Kingdom,< 30 minutes,Jay Roach,"Mary Ruth Clarke, John Hamburg, Greg Glienna, ...","Ben Stiller, Robert De Niro, Blythe Danner, Te...",...,84.0,73.0,15.0,"$166,244,045",NaT,NaT,https://www.netflix.com/watch/81297900,311557.0,166244045.0,True
1925,Id like to Borrow a Girlfriend,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Series,2.8,Japan,< 30 minutes,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",NaT,NaT,https://www.netflix.com/watch/81299211,733336.0,474544677.0,True
2128,Its Okay to Not Be Okay,Horror,"English, Hebrew",Series,3.8,"Lithuania,Mexico,India,South Korea,Russia,Unit...",< 30 minutes,Andy Muschietti,"Gary Dauberman, Chase Palmer, Stephen King, Ca...","Sophia Lillis, Finn Wolfhard, Jaeden Martell, ...",...,86.0,69.0,47.0,"$328,828,874",NaT,NaT,https://www.netflix.com/watch/81243992,460854.0,328828874.0,True
3160,Angel Heart,"Horror, Mystery, Thriller","English, French",Series,3.5,Japan,< 30 minutes,Alan Parker,"Alan Parker, William Hjortsberg","Mickey Rourke, Lisa Bonet, Robert De Niro, Cha...",...,79.0,61.0,4.0,"$17,185,632",NaT,NaT,https://www.netflix.com/watch/81253333,80843.0,17185632.0,True
3259,Snowpiercer,"Action, Drama, Sci-Fi","English, Korean, French, Japanese, Czech, German",Series,4.1,"United Kingdom,Russia,Lithuania,Canada,South A...",< 30 minutes,Bong Joon Ho,"Bong Joon Ho, Kelly Masterson, Jean-Marc Roche...","John Hurt, Ed Harris, Chris Evans, Kang-ho Song",...,94.0,84.0,105.0,"$4,563,650",NaT,NaT,https://www.netflix.com/watch/80177458,322589.0,4563650.0,True
3560,Sing Yesterday for Me,"Animation, Comedy, Family, Musical","English, Japanese, Ukrainian",Series,3.4,"Japan,Thailand,Singapore,Malaysia",< 30 minutes,"Christophe Lourdelet, Garth Jennings",Garth Jennings,"Scarlett Johansson, Reese Witherspoon, Seth Ma...",...,72.0,59.0,25.0,"$270,448,425",NaT,NaT,https://www.netflix.com/watch/81266992,134434.0,270448425.0,True
3842,Babies,Documentary,"English, Japanese, Mongolian",Series,4.9,"Brazil,Belgium,Mexico,Portugal,Switzerland,Uni...",< 30 minutes,Thomas Balmès,"Alain Chabat, Thomas Balmès","Bayar, Hattie, Ponijao, Mari",...,67.0,63.0,3.0,"$7,320,323",NaT,NaT,https://www.netflix.com/watch/80117833,6969.0,7320323.0,True
4515,Im with the Band: Nasty Cherry,"Action, Adventure, Fantasy, Sci-Fi","English, Sanskrit",Series,2.8,"Mexico,Brazil,Lithuania,Slovakia,Turkey,United...",< 30 minutes,George Lucas,George Lucas,"Liam Neeson, Ewan McGregor, Natalie Portman, J...",...,52.0,51.0,69.0,"$474,544,677",NaT,NaT,https://www.netflix.com/watch/80217594,733336.0,474544677.0,True
5730,The Hateful Eight: Extended Version,"Crime, Drama, Mystery, Thriller, Western","English, Spanish, French",Series,3.7,United States,< 30 minutes,Quentin Tarantino,Quentin Tarantino,"Walton Goggins, Samuel L. Jackson, Jennifer Ja...",...,74.0,68.0,116.0,"$54,117,416",NaT,NaT,https://www.netflix.com/watch/80174683,520333.0,54117416.0,True
8044,The Terminal,"Comedy, Drama, Romance","English, Bulgarian, Spanish, Russian, Mandarin...",Series,3.2,"Australia,India,Canada,United Kingdom,United S...",< 30 minutes,Steven Spielberg,"Jeff Nathanson, Andrew Niccol, Sacha Gervasi","Stanley Tucci, Chi McBride, Catherine Zeta-Jon...",...,61.0,55.0,8.0,"$77,872,883",NaT,NaT,https://www.netflix.com/watch/81049739,408150.0,77872883.0,True
8123,Paprika,"Animation, Drama, Fantasy, Mystery, Sci-Fi, Th...","Japanese, English",Series,4.0,"Australia,Canada,Singapore,Hong Kong,Thailand,...",< 30 minutes,Satoshi Kon,"Yasutaka Tsutsui, Seishi Minakami, Satoshi Kon","Kôichi Yamadera, Tôru Furuya, Megumi Hayashiba...",...,84.0,81.0,5.0,"$882,267",NaT,NaT,https://www.netflix.com/watch/80189656,71845.0,882267.0,False

### 11) Find all movies which are available in Japan and fall in multiple genres.

In [115]:
data[(data['Series or Movie'] == 'Movie') & (data['Genre'].str.contains(',', na=False))&(data['Country Availability'].str.contains('Japan',na=False))]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Rotten Tomatoes Score,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit
97,The Girl on the Train,"Crime, Drama, Mystery, Thriller","English, Spanish",Movie,2.6,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",> 2 hrs,Tate Taylor,"Paula Hawkins, Erin Cressida Wilson","Emily Blunt, Justin Theroux, Rebecca Ferguson,...",...,44.0,48.0,12.0,"$75,395,035",NaT,NaT,https://www.netflix.com/watch/81144153,169614.0,75395035.0,True
99,Ride Your Wave,"Animation, Comedy, Drama, Family, Fantasy, Rom...",Japanese,Movie,7.9,Japan,1-2 hour,Masaaki Yuasa,Reiko Yoshida,"Kentaro Ito, Honoka Matsumoto, Rina Kawaei, Ry...",...,93.0,63.0,3.0,"$332,432",NaT,NaT,https://www.netflix.com/watch/81253737,1601.0,332432.0,False
110,Red,"Action, Comedy, Crime, Thriller","English, Russian",Movie,3.4,"Canada,Mexico,South Africa,Thailand,Singapore,...",> 2 hrs,Robert Schwentke,"Cully Hamner, Warren Ellis, Erich Hoeber, Jon ...","Bruce Willis, Jefferson Brown, Mary-Louise Par...",...,72.0,60.0,19.0,"$90,380,162",NaT,NaT,https://www.netflix.com/watch/81408627,290548.0,90380162.0,True
125,Love,"Drama, Romance","English, French",Movie,2.5,"Canada,Mexico,South Africa,Thailand,Singapore,...",1-2 hour,Gaspar Noé,Gaspar Noé,"Klara Kristin, Ugo Fox, Karl Glusman, Aomi Muyock",...,40.0,51.0,1.0,"$249,083",NaT,NaT,https://www.netflix.com/watch/81365135,48843.0,249083.0,False
262,Sonic the Hedgehog,"Action, Adventure, Comedy, Sci-Fi","English, French",Movie,2.9,"Russia,Japan",1-2 hour,Jeff Fowler,"Josh Miller, Pat Casey","Tika Sumpter, James Marsden, Ben Schwartz, Jim...",...,63.0,47.0,6.0,"$148,974,665",NaT,NaT,https://www.netflix.com/watch/80217006,89305.0,148974665.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9020,Ghostbusters,"Action, Comedy, Fantasy, Sci-Fi",English,Movie,3.3,"Japan,South Korea,Portugal,Canada,Switzerland,...",1-2 hour,Paul Feig,"Harold Ramis, Ivan Reitman, Katie Dippold, Dan...","Zach Woods, Kristen Wiig, Charles Dance, Ed Be...",...,74.0,60.0,24.0,"$128,350,574",NaT,NaT,https://www.netflix.com/watch/80080514,204928.0,128350574.0,True
9038,Good Time,"Crime, Drama, Thriller",English,Movie,4.1,"Australia,Russia,Singapore,Sweden,Poland,Lithu...",1-2 hour,"Benny Safdie, Josh Safdie","Ronald Bronstein, Josh Safdie","Robert Pattinson, Benny Safdie, Buddy Duress, ...",...,92.0,80.0,49.0,"$2,026,499",NaT,NaT,https://www.netflix.com/watch/80191344,91250.0,2026499.0,True
9061,A Ghost Story,"Drama, Fantasy, Romance","English, Spanish",Movie,4.1,"United States,Japan,Switzerland,France",1-2 hour,David Lowery,David Lowery,"Rooney Mara, Casey Affleck, Kenneisha Thompson...",...,91.0,84.0,20.0,"$1,596,371",NaT,NaT,https://www.netflix.com/watch/80173542,61150.0,1596371.0,False
9192,Risen,"Action, Drama, History, Mystery",English,Movie,2.8,"Japan,Switzerland,Brazil,Spain,Italy,Argentina...",1-2 hour,Kevin Reynolds,"Paul Aiello, Kevin Reynolds","Joseph Fiennes, Cliff Curtis, Tom Felton, Pete...",...,53.0,51.0,3.0,"$36,880,033",NaT,NaT,https://www.netflix.com/watch/80071345,25315.0,36880033.0,True
9221,The Foreigner,"Action, Thriller","English, Mandarin",Movie,3.2,"United Kingdom,Australia,South Korea,Turkey,Hu...",1-2 hour,Martin Campbell,"Stephen Leather, David Marconi","Mark Tandy, Rufus Jones, Katie Leung, Jackie Chan",...,65.0,55.0,1.0,"$34,393,507",NaT,NaT,https://www.netflix.com/watch/80185765,102492.0,34393507.0,True

### 12) Total Rating of a film means the sum of Hidden Gem Score and IMDB Score. Find all films which have a combined total rating of at least 15.

In [116]:
data["Total Rating"] = data['IMDb Score']+data['Hidden Gem Score']

In [117]:
data[data["Total Rating"]>=15]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit,Total Rating
62,Paths of the Soul,Drama,Tibetan,Movie,8.9,South Korea,1-2 hour,Yang Zhang,Yang Zhang,"Pei Yang, Tsring Chodron, Tsewang Dolkar, Jian...",...,90.0,7.0,"$31,747",NaT,NaT,https://www.netflix.com/watch/80084094,738.0,31747.0,False,16.4
400,Midnight Family,"Documentary, Action, Crime, Drama",Spanish,Movie,8.5,"Mexico,Argentina,Colombia",1-2 hour,Luke Lorentzen,Luke Lorentzen,"Manuel Hernandez, Juan Ochoa, Fer Ochoa, Josue...",...,81.0,26.0,"$42,310",NaT,NaT,https://www.netflix.com/watch/81117674,1412.0,42310.0,False,15.9
602,Grizzlies,"Biography, Drama","Inuktitut, English",Movie,8.2,United States,1-2 hour,Miranda de Pencier,"Moira Walley-Beckett, Graham Yost","Seth Burke, Mary Buscemi, Jack Anawak, Fred Ba...",...,69.0,9.0,"$11,650",NaT,NaT,https://www.netflix.com/watch/81019033,1314.0,11650.0,False,15.7
676,Gilberts Grim Revenge,"Documentary, Biography, Comedy",English,Movie,8.7,Sweden,1-2 hour,Neil Berkeley,"James Leche, Neil Berkeley","Joy Behar, Dave Attell, Richard Belzer, Gilber...",...,73.0,1.0,"$8,362",NaT,NaT,https://www.netflix.com/watch/81351677,716.0,8362.0,False,16.2
1200,Amandla! A Revolution in Four Part Harmony,"Documentary, History, Music","English, Zulu",Movie,8.6,United States,1-2 hour,Lee Hirsch,Lee Hirsch,"F.W. de Klerk, Jesse Jackson, Abdullah Ibrahim...",...,78.0,7.0,"$405,331",NaT,NaT,https://www.netflix.com/watch/60025029,562.0,405331.0,False,16.0
1777,Be with Me,"Drama, Romance","Cantonese, English, Hokkien, Mandarin",Movie,8.0,"Thailand,Singapore,Malaysia",1-2 hour,Eric Khoo,"Theresa Poh Lin Chan, Eric Khoo, Kim Hoh Wong","Theresa Poh Lin Chan, Leong Kooi Eng, Chiew Su...",...,67.0,7.0,"$1,365",NaT,NaT,https://www.netflix.com/watch/70058486,1631.0,1365.0,False,15.0
3673,Bethany Hamilton: Unstoppable,"Documentary, Sport",English,Movie,8.1,"Thailand,Romania,Spain,Mexico,Switzerland,Cana...",1-2 hour,Aaron Lieber,"Aaron Lieber, Carol Martori","Adam Dirks, Alana Blanchard, Tobias Dirks, Bet...",...,55.0,1.0,"$590,671",NaT,NaT,https://www.netflix.com/watch/81097552,556.0,590671.0,False,15.5
4016,Autumn Spring,"Comedy, Drama, Family","Czech, Slovak",Movie,8.1,"Czech Republic,Slovakia",1-2 hour,Vladimír Michálek,Jirí Hubac,"Ondrej Vetchý, Stanislav Zindulka, Vlastimil B...",...,68.0,6.0,"$96,269",NaT,NaT,https://www.netflix.com/watch/60029194,1721.0,96269.0,False,15.6
4190,Penguin Highway,"Animation, Adventure, Family, Fantasy, Mystery","Japanese, English",Movie,8.2,"Japan,South Korea,Italy",1-2 hour,Hiroyasu Ishida,"Makoto Ueda, Tomihiko Morimi","Yû Aoi, Tony Azzolino, Kana Kita, Landen Beattie",...,82.0,4.0,"$104,567",NaT,NaT,https://www.netflix.com/watch/81037598,2074.0,104567.0,False,15.3
4557,Beauty in Trouble,"Comedy, Drama",Czech,Movie,8.4,Slovakia,1-2 hour,Jan Hrebejk,"Robert Graves, Petr Jarchovský","Jana Brejchová, Josef Abrhám, Jirí Schmitzer, ...",...,75.0,6.0,"$19,300",NaT,NaT,https://www.netflix.com/watch/70100376,894.0,19300.0,False,15.2
5603,The Day He Arrives,"Comedy, Drama",Korean,Movie,8.0,South Korea,1-2 hour,Sang-soo Hong,Sang-soo Hong,"Bo-kyeong Kim, Joon-Sang Yoo, Sang-Jung Kim, S...",...,83.0,5.0,"$13,746",NaT,NaT,https://www.netflix.com/watch/70189499,2204.0,13746.0,False,15.0
6087,Pick of the Litter,Documentary,English,Movie,8.3,"United States,United Kingdom",1-2 hour,"Don Hardy, Dana Nachman",Dana Nachman,"Sharon Kret, Janet Gearheart, Diane Meer, Terr...",...,64.0,4.0,"$578,717",NaT,NaT,https://www.netflix.com/watch/81004438,1279.0,578717.0,False,15.8
6892,Heneral Luna,"Action, Biography, History, War","Filipino, Tagalog, English, Spanish",Movie,7.5,"Australia,Japan,Singapore,India,Russia,Lithuan...",1-2 hour,Jerrold Tarog,"Sumaquel P. Hosalla, Henry Francia, Vivencio R...","John Arcilla, Bing Pimentel, Mon Confiado, Arr...",...,58.0,19.0,"$206,040",NaT,NaT,https://www.netflix.com/watch/80084834,1889.0,206040.0,False,15.0

### 13) A Dramatic film means a film which is under Drama Genre. Find all dramatic TV Series which came from the country Japan.

In [118]:
data[(data['Genre'].str.contains("Drama",na = False))& (data['Series or Movie']=="Series")&(data['Country Availability'].str.contains("Japan",na = False))]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit,Total Rating
405,My Girl,"Comedy, Drama, Family, Romance",English,Series,3.0,Japan,< 30 minutes,Howard Zieff,Laurice Elehwany,"Anna Chlumsky, Macaulay Culkin, Jamie Lee Curt...",...,56.0,5.0,"$59,489,799",NaT,NaT,https://www.netflix.com/watch/80999062,72575.0,59489799.0,True,9.9
490,Evils Wave,Drama,"Swedish, Finnish",Series,3.5,Japan,< 30 minutes,Mikael Håfström,"Hans Gunnarsson, Jan Guillou, Mikael Håfström","Henrik Lundström, Linda Zilliacus, Andreas Wil...",...,61.0,10.0,"$15,530",NaT,NaT,https://www.netflix.com/watch/81367819,35722.0,15530.0,False,11.3
1125,The Liberator,"Biography, Drama, History","Spanish, English, French",Series,5.1,"Lithuania,Australia,United Kingdom,Poland,Braz...",< 30 minutes,Alberto Arvelo,Timothy J. Sexton,"Juana Acosta, Edgar Ramírez, Erich Wildpret, M...",...,51.0,3.0,"$113,067",NaT,NaT,https://www.netflix.com/watch/81019775,5038.0,113067.0,False,11.9
1162,Love & Anarchy,"Drama, Romance","English, French",Series,2.5,"Lithuania,Mexico,Australia,Poland,France,Brazi...",< 30 minutes,Gaspar Noé,Gaspar Noé,"Klara Kristin, Ugo Fox, Karl Glusman, Aomi Muyock",...,51.0,1.0,"$249,083",NaT,NaT,https://www.netflix.com/watch/81069541,48843.0,249083.0,False,8.6
1242,The Queens Gambit,"Biography, Drama, History","English, German, French",Series,4.3,"Lithuania,Canada,Australia,Poland,Mexico,Franc...",< 30 minutes,Stephen Frears,Peter Morgan,"Alex Jennings, Roger Allam, James Cromwell, He...",...,91.0,97.0,"$56,441,711",NaT,NaT,https://www.netflix.com/watch/80234304,104495.0,56441711.0,True,11.6
1417,Dragons Dogma,"Action, Crime, Drama, Thriller",Mandarin,Series,3.6,"Russia,Canada,Lithuania,Australia,Poland,Mexic...",< 30 minutes,Peter Ho-Sun Chan,"Oi Wah Lam, Joyce Chan","Tang Wei, Wei Zheng, Jia-Min Li, Donnie Yen",...,62.0,21.0,"$11,137",NaT,NaT,https://www.netflix.com/watch/80992784,13870.0,11137.0,False,10.7
1458,The Duchess,"Biography, Drama, History, Romance",English,Series,3.2,"Lithuania,Canada,Australia,Poland,Mexico,Franc...",< 30 minutes,Saul Dibb,"Anders Thomas Jensen, Jeffrey Hatcher, Amanda ...","Dominic Cooper, Ralph Fiennes, Keira Knightley...",...,62.0,21.0,"$13,848,978",NaT,NaT,https://www.netflix.com/watch/80223040,78504.0,13848978.0,True,10.1
1567,Outbreak,"Action, Drama, Thriller","English, Korean, French",Series,3.1,Japan,< 30 minutes,Wolfgang Petersen,"Robert Roy Pool, Laurence Dworet","Dustin Hoffman, Rene Russo, Morgan Freeman, Ke...",...,64.0,5.0,"$67,659,560",NaT,NaT,https://www.netflix.com/watch/81314896,120516.0,67659560.0,True,9.7
1610,Chefs Table: BBQ,"Adventure, Comedy, Drama","English, Spanish",Series,3.8,"Lithuania,Canada,Australia,Poland,Mexico,Brazi...",< 30 minutes,Jon Favreau,Jon Favreau,"John Leguizamo, Jon Favreau, Emjay Anthony, Bo...",...,68.0,4.0,"$31,424,003",NaT,NaT,https://www.netflix.com/watch/81292974,197249.0,31424003.0,True,11.1
1949,About Time,"Comedy, Drama, Fantasy, Romance, Sci-Fi",English,Series,3.4,"Japan,South Korea,Hong Kong,Thailand,South Afr...",< 30 minutes,Richard Curtis,Richard Curtis,"Bill Nighy, Rachel McAdams, Domhnall Gleeson, ...",...,55.0,9.0,"$15,322,921",NaT,NaT,https://www.netflix.com/watch/81267762,304576.0,15322921.0,True,11.2
3259,Snowpiercer,"Action, Drama, Sci-Fi","English, Korean, French, Japanese, Czech, German",Series,4.1,"United Kingdom,Russia,Lithuania,Canada,South A...",< 30 minutes,Bong Joon Ho,"Bong Joon Ho, Kelly Masterson, Jean-Marc Roche...","John Hurt, Ed Harris, Chris Evans, Kang-ho Song",...,84.0,105.0,"$4,563,650",NaT,NaT,https://www.netflix.com/watch/80177458,322589.0,4563650.0,True,11.2
4114,The Circle,"Drama, Sci-Fi, Thriller",English,Series,1.8,"Lithuania,Portugal,Belgium,Spain,Turkey,Greece...",< 30 minutes,James Ponsoldt,"James Ponsoldt, Dave Eggers","Emma Watson, Ellar Coltrane, Bill Paxton, Glen...",...,43.0,1.0,"$20,497,844",NaT,NaT,https://www.netflix.com/watch/81044551,85020.0,20497844.0,True,7.1
8008,The Outsiders,"Crime, Drama",English,Series,2.9,"Australia,Singapore,Russia,Lithuania,India,Slo...",< 30 minutes,Francis Ford Coppola,"S.E. Hinton, Kathleen Rowell","Ralph Macchio, Patrick Swayze, C. Thomas Howel...",...,41.0,4.0,"$25,697,647",NaT,NaT,https://www.netflix.com/watch/81072883,75887.0,25697647.0,True,10.0

### 14) Find all films which were directed by a person whose name starts with C.

In [119]:
data[data["Director"].str.startswith("C")]

,Title,Genre,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,Actors,...,Metacritic Score,Awards Nominated For,Boxoffice,Release Date,Netflix Release Date,Netflix Link,IMDb Votes,Gross,hit,Total Rating
154,The Flower of Evil,Drama,French,Movie,6.8,France,1-2 hour,Claude Chabrol,"Louise L. Lambrichs, Claude Chabrol, Caroline ...","Nathalie Baye, Suzanne Flon, Benoît Magimel, B...",...,67.0,2.0,"$182,163",NaT,NaT,https://www.netflix.com/watch/60031237,2966.0,182163.0,False,13.3
478,Lizzie,"Biography, Crime, Drama, Mystery, Thriller",English,Movie,4.9,South Korea,1-2 hour,Craig William Macneill,Bryce Kass,"Fiona Shaw, Jeff Perry, Chloë Sevigny, Kristen...",...,59.0,1.0,"$642,157",NaT,NaT,https://www.netflix.com/watch/80240396,6399.0,642157.0,False,10.7
487,High Life,"Adventure, Drama, Horror, Mystery, Sci-Fi, Thr...",English,Movie,3.6,South Korea,1-2 hour,Claire Denis,"Claire Denis, Geoff Cox, Nick Laird, Andrew Li...","Robert Pattinson, Mia Goth, Juliette Binoche, ...",...,77.0,15.0,"$1,225,852",NaT,NaT,https://www.netflix.com/watch/81032217,29177.0,1225852.0,False,9.4
1050,Birds of Prey (And the Fantabulous Emancipatio...,"Action, Adventure, Comedy, Crime","English, Chinese",Movie,3.3,"Japan,Australia,Sweden",1-2 hour,Cathy Yan,"Bruce Timm, Christina Hodson, Paul Dini","Margot Robbie, Jurnee Smollett, Mary Elizabeth...",...,60.0,38.0,"$84,158,461",NaT,NaT,https://www.netflix.com/watch/81165134,168176.0,84158461.0,True,9.4
1893,Extreme Ops,"Action, Adventure, Thriller","English, German, Japanese, Serbo-Croatian",Movie,3.5,"Czech Republic,Slovakia",1-2 hour,Christian Duguay,"Timothy Scott Bogart, Michael Zaidan, Mark Mullin","Bridgette Wilson-Sampras, Rufus Sewell, Devon ...",...,17.0,1.0,"$4,842,259",NaT,NaT,https://www.netflix.com/watch/60024933,5333.0,4842259.0,True,8.0
2040,Rio,"Animation, Adventure, Comedy, Crime, Family, M...","English, Portuguese",Movie,3.4,"South Korea,Hong Kong,Thailand,Singapore,Malaysia",1-2 hour,Carlos Saldanha,"Sam Harper, Earl Richey Jones, Jennifer Ventim...","Sofia Scarpa Saldanha, Karen Disher, Leslie Ma...",...,63.0,31.0,"$143,619,809",NaT,NaT,https://www.netflix.com/watch/70138804,206870.0,143619809.0,True,10.3
2511,22 минуты,"Action, Comedy, Crime",English,Movie,3.8,Russia,1-2 hour,"Christopher Miller, Phil Lord","Jonah Hill, Stephen J. Cannell, Michael Bacall...","Wyatt Russell, Channing Tatum, Peter Stormare,...",...,71.0,24.0,"$191,719,337",NaT,NaT,https://www.netflix.com/watch/81333999,346712.0,191719337.0,True,10.8
3350,Ophelia,"Drama, History, Romance, Thriller, War","English, Norwegian, Latin",Movie,4.2,"United Kingdom,Canada,Japan",1-2 hour,Claire McCarthy,"William Shakespeare, Lisa Klein, Semi Chellas","Nathaniel Parker, Calum O'Rourke, Mia Quiney, ...",...,60.0,4.0,"$50,722",NaT,NaT,https://www.netflix.com/watch/81123068,7790.0,50722.0,False,10.8
3560,Sing Yesterday for Me,"Animation, Comedy, Family, Musical","English, Japanese, Ukrainian",Series,3.4,"Japan,Thailand,Singapore,Malaysia",< 30 minutes,"Christophe Lourdelet, Garth Jennings",Garth Jennings,"Scarlett Johansson, Reese Witherspoon, Seth Ma...",...,59.0,25.0,"$270,448,425",NaT,NaT,https://www.netflix.com/watch/81266992,134434.0,270448425.0,True,10.5
3603,The Ruins,"Adventure, Fantasy, Horror, Mystery, Sci-Fi, T...","English, Maya, Spanish, Greek, German",Movie,2.5,"Japan,India",1-2 hour,Carter Smith,Scott B. Smith,"Shawn Ashmore, Jena Malone, Laura Ramsey, Jona...",...,44.0,7.0,"$17,432,844",NaT,NaT,https://www.netflix.com/watch/70084793,70544.0,17432844.0,True,8.4
3787,The Death of Mr. Lazarescu,"Comedy, Drama",Romanian,Movie,4.3,"Switzerland,Mexico,Romania,South Africa,Belgiu...",> 2 hrs,Cristi Puiu,"Razvan Radulescu, Cristi Puiu","Doru Ana, Alina Berzunteanu, Monica Barladeanu...",...,86.0,14.0,"$80,301",NaT,NaT,https://www.netflix.com/watch/70041148,13814.0,80301.0,False,12.2
3788,Aurora,Drama,Romanian,Movie,7.6,"Switzerland,Romania,Mexico,South Africa,Belgiu...",> 2 hrs,Cristi Puiu,Cristi Puiu,"Clara Voda, Cristi Puiu, Valeria Seciu, Catrin...",...,63.0,8.0,"$5,677",NaT,NaT,https://www.netflix.com/watch/70139563,1728.0,5677.0,False,14.2
4100,Missing Link,"Animation, Adventure, Comedy, Family, Fantasy","English, Spanish, Tibetan",Movie,3.7,"United Kingdom,Hungary,Czech Republic,Australi...",1-2 hour,Chris Butler,Chris Butler,"David Walliams, Hugh Jackman, Stephen Fry, Mat...",...,68.0,44.0,"$16,649,539",NaT,NaT,https://www.netflix.com/watch/81034936,22105.0,16649539.0,True,10.4
4105,The Hustle,"Comedy, Crime","English, German, Dutch, Danish, French, Americ...",Movie,1.7,United Kingdom,1-2 hour,Chris Addison,"Jac Schaeffer, Stanley Shapiro, Dale Launer, P...","Timothy Simons, Ashley McGuire, Rebel Wilson, ...",...,35.0,3.0,"$35,417,038",NaT,NaT,https://www.netflix.com/watch/81209142,47958.0,35417038.0,True,7.1
4144,John Wick: Chapter 3 - Parabellum,"Action, Crime, Thriller","English, Russian, Japanese, Indonesian, Mandar...",Movie,3.9,"United Kingdom,Hungary,Netherlands,Czech Repub...",> 2 hrs,Chad Stahelski,"Derek Kolstad, Chris Collins, Shay Hatten, Mar...","Ian McShane, Laurence Fishburne, Keanu Reeves,...",...,73.0,26.0,"$171,015,687",NaT,NaT,https://www.netflix.com/watch/81168939,278016.0,171015687.0,True,11.3
4308,Happy Death Day 2U,"Comedy, Horror, Mystery, Sci-Fi, Thriller","English, French",Movie,3.2,"Russia,Australia,Poland,Sweden,Turkey,Israel,L...",1-2 hour,Christopher Landon,"Scott Lobdell, Christopher Landon","Jessica Rothe, Suraj Sharma, Israel Broussard,...",...,57.0,4.0,"$28,148,130",NaT,NaT,https://www.netflix.com/watch/81035064,59148.0,28148130.0,True,9.4
4332,Light of My Life,"Drama, Sci-Fi, Thriller",English,Movie,3.6,Canada,1-2 hour,Casey Affleck,Casey Affleck,"Casey Affleck, Elisabeth Moss, Tom Bower, Anna...",...,67.0,5.0,"$20,056",NaT,NaT,https://www.netflix.com/watch/80222641,10779.0,20056.0,False,10.2
4334,12:08 East of Bucharest,"Comedy, Drama",Romanian,Movie,5.5,Romania,1-2 hour,Corneliu Porumboiu,Corneliu Porumboiu,"Teodor Corban, Mircea Andreescu, Mirela Cioaba...",...,77.0,13.0,"$91,881",NaT,NaT,https://www.netflix.com/watch/70059032,7171.0,91881.0,False,12.9
4578,Thoroughbreds,"Comedy, Crime, Drama, Thriller",English,Movie,3.8,"Canada,Brazil,Portugal,Argentina,Mexico,Colomb...",1-2 hour,Cory Finley,Cory Finley,"Anton Yelchin, Anya Taylor-Joy, Olivia Cooke, ...",...,75.0,21.0,"$3,072,605",NaT,NaT,https://www.netflix.com/watch/80172007,35682.0,3072605.0,True,10.5
4604,Ferdinand,"Animation, Adventure, Comedy, Family, Fantasy","English, Spanish, German",Movie,3.3,"Switzerland,Germany",1-2 hour,Carlos Saldanha,"Robert L. Baird, Robert Lawson, David Kidd, Ro...","Jack Gore, Colin H. Murphy, Nile Diaz, Jet Jur...",...,58.0,20.0,"$84,410,380",NaT,NaT,https://www.netflix.com/watch/80191879,48883.0,84410380.0,True,10.0
4674,The Mule,"Crime, Drama, Thriller","English, Spanish",Movie,3.3,"Portugal,Canada,Switzerland,Belgium,Hungary,Cz...",1-2 hour,Clint Eastwood,"Nick Schenk, Sam Dolnick","Cesar De León, Patrick L. Reyes, Clint Eastwoo...",...,58.0,10.0,"$103,804,407",NaT,NaT,https://www.netflix.com/watch/81035551,113799.0,103804407.0,True,10.3
4794,Mortal Engines,"Action, Adventure, Fantasy, Sci-Fi, Thriller",English,Movie,2.2,"Lithuania,Israel,Poland,Greece,Turkey,Thailand...",> 2 hrs,Christian Rivers,"Philippa Boyens, Philip Reeve, Fran Walsh, Pet...","Hera Hilmar, Robert Sheehan, Hugo Weaving, Jihae",...,44.0,3.0,"$15,951,040",NaT,NaT,https://www.netflix.com/watch/81002746,110107.0,15951040.0,True,8.3
5146,The Rider,"Drama, Western","English, Spanish, Sioux",Movie,4.4,"Japan,Australia",1-2 hour,Chloé Zhao,Chloé Zhao,"Lilly Jandreau, Brady Jandreau, Tim Jandreau, ...",...,92.0,44.0,"$2,419,031",NaT,NaT,https://www.netflix.com/watch/80194284,14277.0,2419031.0,True,11.8
5380,The Nun,"Horror, Mystery, Thriller","English, French, Romanian, Latin",Movie,2.1,"Hong Kong,Thailand,Singapore,India,Malaysia,Tu...",1-2 hour,Corin Hardy,"Gary Dauberman, James Wan","Jonas Bloquet, Bonnie Aarons, Demián Bichir, T...",...,46.0,1.0,"$117,450,119",NaT,NaT,https://www.netflix.com/watch/80233862,119020.0,117450119.0,True,7.4
5457,Happy Death Day,"Comedy, Horror, Mystery, Thriller",English,Movie,3.2,"France,Switzerland,Italy",1-2 hour,Christopher Landon,Scott Lobdell,"Ruby Modine, Jessica Rothe, Charles Aitken, Is...",...,58.0,3.0,"$55,683,845",NaT,NaT,https://www.netflix.com/watch/80188939,117376.0,55683845.0,True,9.8
5483,Blindspotting,"Comedy, Crime, Drama",English,Movie,4.1,Turkey,1-2 hour,Carlos López Estrada,"Daveed Diggs, Rafael Casal","Jasmine Cephas Jones, Janina Gavankar, Rafael ...",...,77.0,18.0,"$4,333,394",NaT,NaT,https://www.netflix.com/watch/80240678,27383.0,4333394.0,True,11.5
5524,Mission: Impossible - Fallout,"Action, Adventure, Thriller","English, French",Movie,4.3,"Hong Kong,India,United Kingdom,Thailand,South ...",> 2 hrs,Christopher McQuarrie,"Bruce Geller, Christopher McQuarrie","Henry Cavill, Ving Rhames, Tom Cruise, Simon Pegg",...,86.0,37.0,"$220,159,104",NaT,NaT,https://www.netflix.com/watch/80236314,292193.0,220159104.0,True,12.0
6325,The Bullet Vanishes,"Action, Adventure, Drama, Mystery, Thriller","Mandarin, Cantonese",Movie,7.7,"Russia,India,Lithuania,United Kingdom,Switzerl...",1-2 hour,Chi-Leung Law,"Sin Ling Yeung, Chi-Leung Law","Ching Wan Lau, Boran Jing, Nicholas Tse, Mi Yang",...,65.0,18.0,"$117,629",NaT,NaT,https://www.netflix.com/watch/70256449,1945.0,117629.0,False,14.3
6409,The Book of Henry,"Crime, Drama, Thriller",English,Movie,2.0,"Italy,Switzerland",1-2 hour,Colin Trevorrow,Gregg Hurwitz,"Naomi Watts, Jaeden Martell, Jacob Tremblay, S...",...,31.0,3.0,"$4,504,974",NaT,NaT,https://www.netflix.com/watch/80095206,24247.0,4504974.0,True,8.6
6814,The 15:17 to Paris,"Biography, Drama, Thriller","English, French, Arabic, German, Dutch",Movie,2.0,"Hong Kong,United Kingdom,Thailand,Singapore,Ma...",1-2 hour,Clint Eastwood,"Alek Skarlatos, Jeffrey E. Stern, Spencer Ston...","Ray Corasani, Spencer Stone, Anthony Sadler, A...",...,45.0,3.0,"$36,276,286",NaT,NaT,https://www.netflix.com/watch/80223080,29390.0,36276286.0,True,7.3
7020,Operation Finale,"Biography, Drama, History, Thriller, War","English, Spanish, French, German",Movie,3.1,"Lithuania,United Kingdom,Canada,Hong Kong,Russ...",> 2 hrs,Chris Weitz,Matthew Orton,"Mélanie Laurent, Lior Raz, Ben Kingsley, Oscar...",...,58.0,1.0,"$17,612,099",NaT,NaT,https://www.netflix.com/watch/80986885,32806.0,17612099.0,True,9.7
7121,Thirteen,Drama,"English, Spanish, Portuguese",Movie,3.6,"Switzerland,Germany",1-2 hour,Catherine Hardwicke,"Nikki Reed, Catherine Hardwicke","Nikki Reed, Evan Rachel Wood, Vanessa Hudgens,...",...,70.0,49.0,"$4,601,043",NaT,NaT,https://www.netflix.com/watch/60029208,79664.0,4601043.0,True,10.4
8305,"I, Tonya","Biography, Comedy, Drama, Sport",English,Movie,4.0,"Japan,Canada,Belgium,Netherlands,Germany,Austr...",1-2 hour,Craig Gillespie,Steven Rogers,"Margot Robbie, Sebastian Stan, Julianne Nichol...",...,77.0,120.0,"$30,014,539",NaT,NaT,https://www.netflix.com/watch/80216993,183143.0,30014539.0,True,11.5
8352,Ice Age,"Animation, Adventure, Comedy, Family, Fantasy",English,Movie,3.5,South Korea,1-2 hour,"Carlos Saldanha, Chris Wedge","Michael Berg, James Bresnahan, Doug Compton, P...","John Leguizamo, Goran Visnjic, Ray Romano, Den...",...,60.0,30.0,"$176,387,405",NaT,NaT,https://www.netflix.com/watch/60022702,443268.0,176387405.0,True,11.0
8377,Ice Age: Dawn of the Dinosaurs,"Animation, Adventure, Comedy, Family, Fantasy",English,Movie,2.7,South Korea,1-2 hour,"Carlos Saldanha, Mike Thurmeier","Michael Berg, Peter Ackerman, Jason Carter Eat...","Karen Disher, Eunice Cho, Maile Flanagan, Harr...",...,50.0,13.0,"$196,573,705",NaT,NaT,https://www.netflix.com/watch/70107121,224642.0,196573705.0,True,9.6
8420,The LEGO Ninjago Movie,"Animation, Action, Adventure, Comedy, Family",English,Movie,2.8,"Brazil,Argentina,Mexico,Colombia,Germany,Turkey",1-2 hour,"Charlie Bean, Bob Logan, Paul Fisher","Dan Hageman, Bob Logan, William Wheeler, Paul ...","Dave Franco, Fred Armisen, Kumail Nanjiani, Ja...",...,55.0,7.0,"$59,281,555",NaT,NaT,https://www.netflix.com/watch/80182219,22614.0,59281555.0,True,8.8
8441,Dunkirk,"Action, Drama, History, Thriller, War","English, French, German",Movie,4.4,"France,Belgium,Switzerland,Brazil,Argentina,Tu...",1-2 hour,Christopher Nolan,Christopher Nolan,"Damien Bonnard, Lee Armstrong, Aneurin Barnard...",...,94.0,228.0,"$189,740,665",NaT,NaT,https://www.netflix.com/watch/80170278,556842.0,189740665.0,True,12.2
8480,Police Story,"Action, Comedy, Crime, Thriller",Cantonese,Movie,4.1,"Hong Kong,Thailand,Singapore,Malaysia",1-2 hour,"Chi-Hwa Chen, Jackie Chan","Edward Tang, Jackie Chan","Maggie Cheung, Yuen Chor, Brigitte Lin, Jackie...",...,78.0,5.0,"$113,164",NaT,NaT,https://www.netflix.com/watch/70056056,29914.0,113164.0,False,11.7
8714,Better Watch Out,"Comedy, Horror, Thriller",English,Movie,3.7,"Switzerland,Germany",1-2 hour,Chris Peckover,"Zack Kahn, Chris Peckover","Aleks Mikic, Ed Oxenbould, Levi Miller, Olivia...",...,67.0,2.0,"$20,369",NaT,NaT,https://www.netflix.com/watch/80191638,32265.0,20369.0,False,10.2
8890,The Bridges of Madison County,"Drama, Romance",English,Movie,3.9,"Japan,Switzerland,Italy",> 2 hrs,Clint Eastwood,"Robert James Waller, Richard LaGravenese","Annie Corley, Clint Eastwood, Victor Slezak, M...",...,69.0,18.0,"$71,516,617",NaT,NaT,https://www.netflix.com/watch/70150462,73431.0,71516617.0,True,11.5
8923,John Wick: Chapter Two,"Action, Crime, Thriller","English, Italian, Russian",Movie,4.0,"Hungary,Romania,Czech Republic,Germany,Argenti...",> 2 hrs,Chad Stahelski,Derek Kolstad,"Ruby Rose, Ian McShane, Riccardo Scamarcio, Ke...",...,75.0,10.0,"$92,029,184",NaT,NaT,https://www.netflix.com/watch/80131552,367362.0,92029184.0,True,11.5
9183,The Lego Batman Movie,"Animation, Action, Comedy, Family",English,Movie,4.0,"France,Belgium,Germany,South Korea,Turkey",1-2 hour,Chris McKay,"Ole Kirk Christiansen, Jerry Siegel, Chris McK...","Ralph Fiennes, Rosario Dawson, Michael Cera, W...",...,75.0,67.0,"$175,750,384",NaT,NaT,https://www.netflix.com/watch/80131731,131509.0,175750384.0,True,11.3
9211,The Nut Job 2: Nutty by Nature,"Animation, Adventure, Comedy, Family, Fantasy",English,Movie,3.8,"South Korea,Romania,Hungary,Brazil,Czech Repub...",1-2 hour,Cal Brunker,"Bob Barlen, Scott Bindley, Peter Lepeniotis, C...","Bobby Moynihan, Maya Rudolph, Bobby Cannavale,...",...,36.0,3.0,"$28,370,522",NaT,NaT,https://www.netflix.com/watch/80067832,5931.0,28370522.0,True,9.3

### 15) Find all films directed by Christopher Nolan whose name ends with O.

In [120]:
data[(data["Director"].str.contains("Christopher Nolan"))&(data['Series or Movie']=="Movie") & (data["Title"].str.endswith("o"))]["Title"]

Series([], Name: Title, dtype: object)

### 16) Find all films which have been directed and written by Christopher Nolan.

In [121]:
data[(data["Director"].str.contains("Christopher Nolan"))&(data['Writer'].str.contains("Christopher Nolan"))]["Title"]

8441    Dunkirk
Name: Title, dtype: object

### 17) Find the English movie name(title) which has IMDB score more than 8.5.

In [122]:
data[(data["Series or Movie"]=="Movie")&(data["Languages"].str.contains("English",na = True))&(data['IMDb Score']>8.5)]["Title"]

865     Fiction.
1595    Parasite
Name: Title, dtype: object